[package]
name = "rezoning-scraper"
version = "3.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
chrono = "0.4.43"
clap = { version = "4.5.54", features = ["derive", "env"] }
scraper = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
reqwest = { version = "0.13.1", features = ["json"] }
indicatif = "0.18.3"
colored = "3.0.0"
tokio = { version = "1", features = ["full"] }
bsky-sdk = "0.1.23"
html2md = "0.2.15"
genai = "0.5.0"
itertools = "0.14.0"
sentry = { version = "0.46.1", features = ["anyhow"] }
image = "0.25.9"

# Force vendored OpenSSL on Linux to make building for musl easier
[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.75", features = ["vendored"]}

# build with `cargo build --profile profiling`
# to analyze performance with tooling like linux perf
[profile.profiling]
inherits = "release"
strip = false
debug = true
