# configuration file for dotnet-releaser
# run with: dotnet-releaser build --force dotnet-releaser.toml

# disable default settings
profile = "custom"

[msbuild]
project = "RezoningScraper/RezoningScraper.csproj"

[msbuild.properties]
PublishTrimmed = true
PublishSingleFile = true
SelfContained = true
PublishReadyToRun = false
CopyOutputSymbolsToPublishDirectory = false
SkipCopyingSymbolsToOutputDirectory = true
DebugType = "embedded"
IncludeNativeLibrariesForSelfExtract = true

[github]
user = "rgwood"
repo = "RezoningScraper"

[changelog]
publish = false

[nuget]
publish = false

[[pack]]
rid = ["win-x64", "win-arm64", "linux-x64", "linux-arm64","osx-x64", "osx-arm64"]
kinds = ["zip"]
